name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gardendoctor_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install

    - name: Setup database
      run: |
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE DATABASE IF NOT EXISTS gardendoctor_test;"

    - name: Set environment variables
      run: |
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_PORT=3307" >> $GITHUB_ENV
        echo "DB_USER=root" >> $GITHUB_ENV
        echo "DB_PASSWORD=root" >> $GITHUB_ENV
        echo "DB_NAME=gardendoctor_test" >> $GITHUB_ENV
        echo "TEST_DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "TEST_DB_PORT=3306" >> $GITHUB_ENV
        echo "TEST_DB_USER=root" >> $GITHUB_ENV
        echo "TEST_DB_PASSWORD=root" >> $GITHUB_ENV
        echo "TEST_DB_NAME=gardendoctor_test" >> $GITHUB_ENV

    - name: Run tests
      run: npm test

    
